name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # npm publish when release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build packages
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd packages/core
          npm publish --access public --provenance
          cd ../react
          npm publish --access public --provenance
          cd ../vue
          npm publish --access public --provenance
          cd ../svelte
          npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
